### ISSUE TITLE
no main()..

### ISSUE THREAD

**Issue by robclark** [simon-budig/shadertoy#4]
I think you need to append something along the lines of:

  void main() { mainImage(gl_FragColor, gl_FragCoord.xy); }

to the end of the shader.. I guess that should probably be done in getshader.py

**Comment by simon-budig** [comment]
yeah, seems something has changed on shadertoy.org. Need to investigate this.

**Comment by robclark** [comment]
fwiw, this seems to do the trick:

-----
diff --git a/getshader.py b/getshader.py
index 5123300..053bd91 100755
--- a/getshader.py
+++ b/getshader.py
@@ -38,6 +38,10 @@ uniform vec4      iDate;                 // (year, month, day, time in secs)
 uniform float     iSampleRate;           // sound sample rate (i.e., 44100)
 \n"""
 
+shaderfooter = """
+void main() { mainImage(gl_FragColor, gl_FragCoord.xy); }
+\n"""
+
 def get_shader (id):
    url = 'https://www.shadertoy.com/shadertoy'
    headers = { 'Referer' : 'https://www.shadertoy.com/' }
@@ -93,6 +97,7 @@ if __name__ == '__main__':
       f.write (shaderinfo % info)
       f.write (shaderdecls)
       f.write (code)
+      f.write (shaderfooter)
       f.close ()
       print ("wrote shader to \"%s\"" % fname, file=sys.stderr)
 
-----

not sure if there is a better way to pick the sampler types..  but anyways, this is pretty cool since I'd been wanting to test freedreno against some of the shadertoy shaders, but with firefox I just get crashes in some unrelated cairo code ;-)

**Comment by simon-budig** [comment]
I have tracked down main() used on shadertoy.com. It additionally ensures that the alpha channel is opaque.

fixed in commit 90f7bd6f87f9d0dda55ab28f07c2682797d4b7b7

**Comment by robclark** [comment]
cool, thx
